import { Transaction } from "./types";

export const sendTransactions: Transaction[] = [
  {
    id: "12dwerkxywurcksc",
    amount: "N200,000",
    status: "success",
    country: "Nigeria",
    route: "Bank Transfer",
    date: "Oct 16, 2025 - 07:22 AM",
    recipient: "Adebisi Lateefat",
    fee: "N20",
    bank: "Wema Bank",
    accountNumber: "0123456789",
    accountName: "Opay",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "failed",
    country: "Nigeria",
    route: "Bank Transfer",
    date: "22/10/25 - 07:22 AM",
    recipient: "John Doe",
    fee: "N10",
    bank: "Access Bank",
    accountNumber: "1234567890",
    accountName: "John Doe",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bank Transfer",
    date: "22/10/25 - 07:22 AM",
    recipient: "Jane Smith",
    fee: "N10",
    bank: "GTBank",
    accountNumber: "0987654321",
    accountName: "Jane Smith",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bank Transfer",
    date: "22/10/25 - 07:22 AM",
    recipient: "Mike Johnson",
    fee: "N10",
    bank: "First Bank",
    accountNumber: "1122334455",
    accountName: "Mike Johnson",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bank Transfer",
    date: "22/10/25 - 07:22 AM",
    recipient: "Sarah Williams",
    fee: "N10",
    bank: "Zenith Bank",
    accountNumber: "5566778899",
    accountName: "Sarah Williams",
    paymentMethod: "Bank Transfer"
  }
];

export const fundTransactions: Transaction[] = [
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Yellow Card",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 1",
    fee: "N10",
    bank: "Yellow Card",
    accountNumber: "1234567890",
    accountName: "User 1",
    paymentMethod: "Yellow Card"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Yellow Card",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 2",
    fee: "N10",
    bank: "Yellow Card",
    accountNumber: "1234567891",
    accountName: "User 2",
    paymentMethod: "Yellow Card"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 3",
    fee: "N10",
    bank: "Conversion",
    accountNumber: "1234567892",
    accountName: "User 3",
    paymentMethod: "Conversion"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Crypto",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 4",
    fee: "N10",
    bank: "Crypto",
    accountNumber: "1234567893",
    accountName: "User 4",
    paymentMethod: "Crypto"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 5",
    fee: "N10",
    bank: "P2P",
    accountNumber: "1234567894",
    accountName: "User 5",
    paymentMethod: "P2P"
  }
];

export const convertTransactions: Transaction[] = [
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    amountSent: "N20,000",
    received: "c1,000",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 1",
    fee: "N10",
    bank: "Conversion",
    accountNumber: "1234567890",
    accountName: "User 1",
    paymentMethod: "Conversion",
    rate: "1N = c1000",
    conversion: "NGN - GHC"
  },
  {
    id: "asdfghjk109876",
    amount: "N30,000",
    amountSent: "N30,000",
    received: "c3,000",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 09:00 AM",
    recipient: "User 2",
    fee: "N15",
    bank: "Conversion",
    accountNumber: "1234567891",
    accountName: "User 2",
    paymentMethod: "Conversion",
    rate: "1N = c1000",
    conversion: "NGN - GHC"
  },
  {
    id: "zxczxqwe456789",
    amount: "N45,000",
    amountSent: "N45,000",
    received: "c4,500",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 08:15 AM",
    recipient: "User 3",
    fee: "N22",
    bank: "Conversion",
    accountNumber: "1234567892",
    accountName: "User 3",
    paymentMethod: "Conversion",
    rate: "1N = c1000",
    conversion: "NGN - GHC"
  },
  {
    id: "qwertyuiop56789",
    amount: "N60,000",
    amountSent: "N60,000",
    received: "c6,000",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 10:30 AM",
    recipient: "User 4",
    fee: "N30",
    bank: "Conversion",
    accountNumber: "1234567893",
    accountName: "User 4",
    paymentMethod: "Conversion",
    rate: "1N = c1000",
    conversion: "NGN - GHC"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N25,000",
    amountSent: "N25,000",
    received: "c2,500",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 11:45 AM",
    recipient: "User 5",
    fee: "N12",
    bank: "Conversion",
    accountNumber: "1234567894",
    accountName: "User 5",
    paymentMethod: "Conversion",
    rate: "1N = c1000",
    conversion: "NGN - GHC"
  }
];

export const withdrawTransactions: Transaction[] = [
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Yellow Card",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 1",
    fee: "N10",
    bank: "Wema Bank",
    accountNumber: "1234567890",
    accountName: "Opay",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Yellow Card",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 2",
    fee: "N10",
    bank: "Wema Bank",
    accountNumber: "1234567891",
    accountName: "Opay",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Conversion",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 3",
    fee: "N10",
    bank: "Wema Bank",
    accountNumber: "1234567892",
    accountName: "Opay",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Crypto",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 4",
    fee: "N10",
    bank: "Wema Bank",
    accountNumber: "1234567893",
    accountName: "Opay",
    paymentMethod: "Bank Transfer"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "User 5",
    fee: "N10",
    bank: "Wema Bank",
    accountNumber: "1234567894",
    accountName: "Opay",
    paymentMethod: "Bank Transfer"
  }
];

export const p2pTransactions: Transaction[] = [
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "Lawal",
    vendorName: "Lawal",
    fee: "N10",
    bank: "P2P",
    accountNumber: "1234567890",
    accountName: "Lawal",
    paymentMethod: "P2P",
    merchantName: "Qamar Malik",
    p2pType: "Crypto Sell",
    usdtAmount: "20 USDT",
    price: "1,500 NGN",
    totalQty: "5.2 USDT",
    txFee: "0",
    txId: "128DJ2I311DJKQKCM",
    orderTime: "Oct 16, 2025 - 07:22AM",
    review: "He is fast and reliable"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "Adewale Saheed",
    vendorName: "Adewale Saheed",
    fee: "N10",
    bank: "P2P",
    accountNumber: "1234567891",
    accountName: "Adewale Saheed",
    paymentMethod: "P2P"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "Chris",
    vendorName: "Chris",
    fee: "N10",
    bank: "P2P",
    accountNumber: "1234567892",
    accountName: "Chris",
    paymentMethod: "P2P"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "Shawnn Michael",
    vendorName: "Shawnn Michael",
    fee: "N10",
    bank: "P2P",
    accountNumber: "1234567893",
    accountName: "Shawnn Michael",
    paymentMethod: "P2P"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "P2P",
    date: "22/10/25 - 07:22 AM",
    recipient: "Anita Baker",
    vendorName: "Anita Baker",
    fee: "N10",
    bank: "P2P",
    accountNumber: "1234567894",
    accountName: "Anita Baker",
    paymentMethod: "P2P"
  }
];

export const billPaymentsTransactions: Transaction[] = [
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bill Payment",
    type: "Airtime",
    date: "22/10/25 - 07:22 AM",
    recipient: "Bill Payment User 1",
    fee: "N10",
    bank: "Bill Payment",
    accountNumber: "BILL001",
    accountName: "Bill Payment User 1",
    paymentMethod: "Bill Payment"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bill Payment",
    type: "Cable tv",
    date: "22/10/25 - 07:22 AM",
    recipient: "Bill Payment User 2",
    fee: "N10",
    bank: "Bill Payment",
    accountNumber: "BILL002",
    accountName: "Bill Payment User 2",
    paymentMethod: "Bill Payment"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bill Payment",
    type: "Data Recharge",
    date: "22/10/25 - 07:22 AM",
    recipient: "Bill Payment User 3",
    fee: "N10",
    bank: "Bill Payment",
    accountNumber: "BILL003",
    accountName: "Bill Payment User 3",
    paymentMethod: "Bill Payment"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bill Payment",
    type: "Electricity",
    date: "22/10/25 - 07:22 AM",
    recipient: "Bill Payment User 4",
    fee: "N10",
    bank: "Bill Payment",
    accountNumber: "BILL004",
    accountName: "Bill Payment User 4",
    paymentMethod: "Bill Payment"
  },
  {
    id: "asdkfj12324kdsk",
    amount: "N20,000",
    status: "success",
    country: "Nigeria",
    route: "Bill Payment",
    type: "Betting",
    date: "22/10/25 - 07:22 AM",
    recipient: "Bill Payment User 5",
    fee: "N10",
    bank: "Bill Payment",
    accountNumber: "BILL005",
    accountName: "Bill Payment User 5",
    paymentMethod: "Bill Payment"
  }
];

