const images = {
  logo: '/src/assets/images/logo.png',
  gymBg: '/src/assets/images/gym_bg.jpg',
  login_bg: '/src/assets/images/login_bg.png',
  shield_tick: '/src/assets/images/shield-tick.png',
  SquaresFour: '/src/assets/images/SquaresFour.png',
  user_icon: '/src/assets/images/user.png',
  transaction_icon: '/src/assets/images/transaction-history.png',
  kyc_icon: '/src/assets/images/security-check.png',
  bitcoin_wallet: '/src/assets/images/bitcoin-wallet.png',
  rates_icon: '/src/assets/images/receipt-dollar.png',
  user_group: '/src/assets/images/user-group.png',
  user_group_icon: '/src/assets/images/user-group.png',
  wallet_icon: '/src/assets/images/wallet-05.png',
  analytics_up: '/src/assets/images/analytics-up.png',
  gift_icon: '/src/assets/images/gift.png',
  customer_support: '/src/assets/images/customer-support.png',
  notification_icon: '/src/assets/images/notification-01.png',
  setting_icon: '/src/assets/images/setting-07.png',
  logout_icon: '/src/assets/images/logout-square-01.png',
  profile_image: '/src/assets/images/Ellipse-66.png',
  Ellipse_67: '/src/assets/images/Ellipse-67.png',
  Ellipse_68: '/src/assets/images/Ellipse-68.png',
  Ellipse_69: '/src/assets/images/Ellipse-69.png',
  UsersThree: '/src/assets/images/UsersThree.png',
  Vector2: '/src/assets/images/Vector2.png',
  Vector3: '/src/assets/images/Vector3.png',
  vector4: '/src/assets/images/Vector4.png',
  analytics_up_green: '/src/assets/images/analytics-up-green.png',
  Rectangle_36: '/src/assets/images/Rectangle-36.png',
  avater1: '/src/assets/images/avater1.png',
  pluscircle: '/src/assets/images/PlusCircle.png',
  flag: '/src/assets/images/flag11.png',
  vector5: '/src/assets/images/Vector5.png',
  SpinnerGap: '/src/assets/images/SpinnerGap.png',
};

export default images;
